{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}-v2
  labels:
   app: {{ .Values.labels.app }}-v2
   version: {{ .Values.labels.version2 }}
{{- end }}