{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}-v1
  labels:
   app: {{ .Values.labels.app }}-v1
   version: {{ .Values.labels.version1 }}
{{- end }}

